/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InheritanceVault } from "./InheritanceVault";
export * as factories from "./factories";
export { InheritanceVault__factory } from "./factories/InheritanceVault__factory";
