/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface InheritanceVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "automationRegistry"
      | "deposit"
      | "executeInheritance"
      | "getStatus"
      | "heir"
      | "inactivityThreshold"
      | "lastPingTimestamp"
      | "owner"
      | "ping"
      | "registerHeir"
      | "setAutomation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutomationSet"
      | "Deposited"
      | "HeirRegistered"
      | "InheritanceExecuted"
      | "Pinged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "automationRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeInheritance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getStatus", values?: undefined): string;
  encodeFunctionData(functionFragment: "heir", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "inactivityThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastPingTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "ping", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerHeir",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAutomation",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "automationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeInheritance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "heir", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "inactivityThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPingTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ping", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerHeir",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAutomation",
    data: BytesLike
  ): Result;
}

export namespace AutomationSetEvent {
  export type InputTuple = [automation: AddressLike];
  export type OutputTuple = [automation: string];
  export interface OutputObject {
    automation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HeirRegisteredEvent {
  export type InputTuple = [heir: AddressLike, threshold: BigNumberish];
  export type OutputTuple = [heir: string, threshold: bigint];
  export interface OutputObject {
    heir: string;
    threshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InheritanceExecutedEvent {
  export type InputTuple = [heir: AddressLike, amount: BigNumberish];
  export type OutputTuple = [heir: string, amount: bigint];
  export interface OutputObject {
    heir: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PingedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InheritanceVault extends BaseContract {
  connect(runner?: ContractRunner | null): InheritanceVault;
  waitForDeployment(): Promise<this>;

  interface: InheritanceVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  automationRegistry: TypedContractMethod<[], [string], "view">;

  deposit: TypedContractMethod<[], [void], "payable">;

  executeInheritance: TypedContractMethod<[], [void], "nonpayable">;

  getStatus: TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint] & {
        _owner: string;
        _heir: string;
        _lastPing: bigint;
        _threshold: bigint;
        _balance: bigint;
      }
    ],
    "view"
  >;

  heir: TypedContractMethod<[], [string], "view">;

  inactivityThreshold: TypedContractMethod<[], [bigint], "view">;

  lastPingTimestamp: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ping: TypedContractMethod<[], [void], "nonpayable">;

  registerHeir: TypedContractMethod<
    [_heir: AddressLike, _threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAutomation: TypedContractMethod<
    [_automation: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "automationRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "executeInheritance"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getStatus"
  ): TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, bigint] & {
        _owner: string;
        _heir: string;
        _lastPing: bigint;
        _threshold: bigint;
        _balance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "heir"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "inactivityThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastPingTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ping"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerHeir"
  ): TypedContractMethod<
    [_heir: AddressLike, _threshold: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAutomation"
  ): TypedContractMethod<[_automation: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AutomationSet"
  ): TypedContractEvent<
    AutomationSetEvent.InputTuple,
    AutomationSetEvent.OutputTuple,
    AutomationSetEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "HeirRegistered"
  ): TypedContractEvent<
    HeirRegisteredEvent.InputTuple,
    HeirRegisteredEvent.OutputTuple,
    HeirRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "InheritanceExecuted"
  ): TypedContractEvent<
    InheritanceExecutedEvent.InputTuple,
    InheritanceExecutedEvent.OutputTuple,
    InheritanceExecutedEvent.OutputObject
  >;
  getEvent(
    key: "Pinged"
  ): TypedContractEvent<
    PingedEvent.InputTuple,
    PingedEvent.OutputTuple,
    PingedEvent.OutputObject
  >;

  filters: {
    "AutomationSet(address)": TypedContractEvent<
      AutomationSetEvent.InputTuple,
      AutomationSetEvent.OutputTuple,
      AutomationSetEvent.OutputObject
    >;
    AutomationSet: TypedContractEvent<
      AutomationSetEvent.InputTuple,
      AutomationSetEvent.OutputTuple,
      AutomationSetEvent.OutputObject
    >;

    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "HeirRegistered(address,uint256)": TypedContractEvent<
      HeirRegisteredEvent.InputTuple,
      HeirRegisteredEvent.OutputTuple,
      HeirRegisteredEvent.OutputObject
    >;
    HeirRegistered: TypedContractEvent<
      HeirRegisteredEvent.InputTuple,
      HeirRegisteredEvent.OutputTuple,
      HeirRegisteredEvent.OutputObject
    >;

    "InheritanceExecuted(address,uint256)": TypedContractEvent<
      InheritanceExecutedEvent.InputTuple,
      InheritanceExecutedEvent.OutputTuple,
      InheritanceExecutedEvent.OutputObject
    >;
    InheritanceExecuted: TypedContractEvent<
      InheritanceExecutedEvent.InputTuple,
      InheritanceExecutedEvent.OutputTuple,
      InheritanceExecutedEvent.OutputObject
    >;

    "Pinged(uint256)": TypedContractEvent<
      PingedEvent.InputTuple,
      PingedEvent.OutputTuple,
      PingedEvent.OutputObject
    >;
    Pinged: TypedContractEvent<
      PingedEvent.InputTuple,
      PingedEvent.OutputTuple,
      PingedEvent.OutputObject
    >;
  };
}
